<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"专家管理",
			            "menuJump":"列表",
			            "tableName":"zhuanji"
			        }
			    ],
			    "menu":"专家管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"项目管理",
			            "menuJump":"列表",
			            "tableName":"xiangmu"
			        }
			    ],
			    "menu":"项目管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"申报管理",
			            "menuJump":"列表",
			            "tableName":"shenbao"
			        }
			    ],
			    "menu":"申报管理"
			}
           ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"项目类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
            
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"项目管理",
			            "menuJump":"列表",
			            "tableName":"xiangmu"
			        }
			    ],
			    "menu":"项目管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
							"通过",
			                "查看",
							"拒绝"
			            ],
			            "menu":"我的工作信息",
			            "menuJump":"列表",
			            "tableName":"shenbao"
			        }
			    ],
			    "menu":"我的工作管理"
			}
	       ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"项目类型管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionary"
	                }
	            ],
	            "menu":"项目类型管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"系统公告管理",
	                    "menuJump":"列表",
	                    "tableName":"xitonggonggao"
	                }
	            ],
	            "menu":"系统公告管理"
	        }
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"专家",
	    "tableName":"zhuanji"
	}
	,
	
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"项目管理",
			            "menuJump":"列表",
			            "tableName":"xiangmu"
			        }
			    ],
			    "menu":"项目管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"申报管理",
			            "menuJump":"列表",
			            "tableName":"shenbao"
			        }
			    ],
			    "menu":"申报管理"
			}
	       ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"项目类型管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionary"
	                }
	            ],
	            "menu":"项目类型管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"系统公告管理",
	                    "menuJump":"列表",
	                    "tableName":"xitonggonggao"
	                }
	            ],
	            "menu":"系统公告管理"
	        }
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	}
	,
	
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
							"新增",
							"修改",
			                "申报"
			            ],
			            "menu":"项目管理",
			            "menuJump":"列表",
			            "tableName":"xiangmu"
			        }
			    ],
			    "menu":"项目管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"申报管理",
			            "menuJump":"列表",
			            "tableName":"shenbao"
			        }
			    ],
			    "menu":"申报管理"
			}
	       ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"项目类型管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionary"
	                }
	            ],
	            "menu":"项目类型管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"系统公告管理",
	                    "menuJump":"列表",
	                    "tableName":"xitonggonggao"
	                }
	            ],
	            "menu":"系统公告管理"
	        }
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
